.gitignore
package.json
src/component/sign/SignUpModal.jsx
src/dataManager/imageS3.js
src/page/MainPage.jsx

회원가입모달 / s3 업로드 분리
- 회원가입모달 / s3 업로드 분리
- 내용을 적어주세요.

feat : 회원가입모달 / s3 업로드 분리

---

src/asset/pic/pause.svg
src/component/main/MainAudioPlayer.jsx
src/component/main/MainPost.jsx
src/component/main/MainPostList.jsx
src/dataManager/useFetch.jsx
src/mocks/handlers.jsx
src/redux/config/index.js
src/redux/slice/mainSlice.js
yarn.lock

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

✨ [#3] 메인 리스트 플레이 버튼, 하단 오디어 플레이어와 동기화

---

src/component/main/MainAudioPlayer.jsx
src/component/main/MainPost.jsx
src/component/main/MainPostList.jsx
src/component/main/MockResource.js
src/index.js
src/redux/slice/mainSlice.js

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

✨ [#3] mainpage Api 연결

---

src/Router.js
src/component/elem/Flex.tsx
src/component/header/Header.jsx
src/component/posting/PostingAudioControlBox.tsx
src/component/posting/PostingCollabReqeusted.tsx
src/component/posting/PostingForm.tsx
src/component/posting/PostingFormCollabo.tsx
src/component/posting/PostingPartSelectModal.tsx
src/dataManager/apiConfig.js
src/dataManager/errorHandler.ts
src/index.js
src/modal/alarm/AlarmModal.tsx
src/model/PostModel.ts
src/model/PostingModel.ts
src/model/ResponseModel.ts
src/page/PostingPage.tsx
src/redux/config/index.ts
src/redux/slice/collaboSlice.ts
src/redux/slice/mainSlice.ts
src/redux/slice/postingSlice.ts
src/redux/slice/userSlice.ts

내용을 적어주세요.
- 내용을 적어주세요.
- 헤더에 유저 프로필 로그인 하면 닉네임이랑[토클 상단] profile image 보이게 바꿔 보았습니다. 
- 다만 아직 모달창 사라질때 데이터 반영이 안되어서 이부분 추후에 로직 추가해야할거 같습니다.

✨ [#15] feat : 콜라보리퀘 - 알람 - 콜라보 승인페이지 - 승인 - 상세페이지 [유저 플로우 연결], 알람 리다이렉팅, 헤더 유저 프로필 전환

---

src/component/modal/Modal.jsx
src/component/sign/SignUpModal.jsx
src/dataManager/imageS3.js

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

feat: 회원가입모달

---

src/component/detail/DetailFollow.jsx
src/component/posting/PostingForm.tsx
src/dataManager/apiConfig.js
src/redux/slice/mainSlice.ts
src/redux/slice/postingSlice.ts

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#15] fix : 머지 오류 처리

---

package.json
src/Router.js
src/component/chat/ChatBubble.tsx
src/component/chat/ChatBubbleList.tsx
src/component/chat/ChatForm.tsx
src/component/chat/ChatRoom.tsx
src/component/chat/ChatRoomItem.tsx
src/component/chat/ChatRoomList.tsx
src/component/elem/Img.tsx
src/component/header/Header.jsx
src/dataManager/apiConfig.js
src/model/ChatModel.ts
src/page/ChatPage.tsx
src/page/PostingPage.tsx
src/styles/theme.ts
yarn.lock

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

✨ Feature/#47

---

package.json
src/component/header/Header.jsx

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

✨ [#15] feat : sse 연결, polyfill 라이브러리 설치, 백엔드 오류 해결 후에 재작업 필요

---

.github/workflows/CICD
src/component/chat/ChatBubbleList.tsx
src/component/chat/ChatForm.tsx
src/component/chat/ChatRoom.tsx
src/component/elem/Flex.tsx
src/component/elem/Textarea.tsx
src/component/header/Header.jsx
src/dataManager/apiConfig.js
src/hook/useTextArea.ts
src/page/ChatPage.tsx
src/page/PostingPage.tsx
src/redux/slice/postingSlice.ts
src/styles/theme.ts
src/util/UserCheck.tsx

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#15] chat form 컴포넌트 추가

---

.github/workflows/CICD.yml
.gitignore
src/asset/pic/index.js
src/component/header/Header.jsx
src/component/posting/PostingForm.tsx
src/component/posting/PostingFormAudio.tsx
src/dataManager/apiConfig.js
yarn.lock

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#45] feat : 배포 자동화 업데이트

---

.github/workflows/CICD.yml

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#45] fix : CICD on 에서 pullRequest 제거

---

.github/workflows/CICD_DEV.yml
src/component/chat/ChatBubble 2.tsx
src/component/chat/ChatBubbleList 2.tsx
src/component/chat/ChatForm 2.tsx
src/component/chat/ChatRoom 2.tsx
src/component/chat/ChatRoomItem 2.tsx
src/component/chat/ChatRoomList 2.tsx
src/component/header/Header.jsx
src/hook/useTextArea 2.ts
src/model/ChatModel 2.ts

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#45] feat : dev, main 배포 자동화 업데이트. sse heartBeat 시간 변경

---

src/component/detail/DetailTop.jsx
src/component/sign/SignInModal.jsx

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#66] 머지 수정

---

src/Router.js
src/component/chat/ChatBubbleList.tsx
src/component/elem/Div.tsx
src/component/elem/Flex.tsx
src/component/elem/Textarea.tsx
src/component/header/Header.jsx
src/component/posting/PostingForm.tsx
src/component/posting/PostingFormAudio.tsx
src/component/posting/PostingFormImage.tsx
src/component/posting/PostingFormImageTItle.tsx
src/component/posting/PostingTitle.tsx
src/dataManager/imageS3.js
src/page/PostingPageNext.tsx
src/redux/slice/postingSlice.ts
src/styles/theme.ts

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#66] refactoring, fix : posting page ui업데이트, image upload 지역 설정 및 오타 수정

---

src/component/header/Header.jsx

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#15] fix : 알람 기능 코드 수정 [추가 수정 필요]

---

package.json
src/App.jsx
src/component/chat/ChatRoom.tsx
src/dataManager/apiConfig.js
yarn.lock

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#47] feat : 소켓 연결 시도중, build  수정

---

.github/workflows/CICD.yml
.github/workflows/CICD_DEV.yml
package.json
yarn.lock

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

edit git actions for kakao features

---

.github/workflows/CICD.yml
.github/workflows/CICD_DEV.yml

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#66] feat : oncounter로 dev브랜치 배포

---

src/App.jsx
src/component/chat/ChatForm.tsx
src/component/chat/ChatList.tsx
src/component/chat/ChatRoomItem.tsx
src/component/chat/ChatRoomList.tsx
src/component/chat/chatSlice.ts
src/component/header/Header.jsx
src/component/main/MainAudioPlayer.tsx
src/hook/useStomp.ts
src/modal/TypeModalWrapper.js

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#47] feat : merged

---

src/component/chat/ChatForm.tsx
src/component/header/Header.jsx

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#47] feat : 채팅 ver1 구현 완료

---

src/component/mypage/MypagePlayList.jsx
src/component/mypage/MypageRight.jsx

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

feat: 애니메이션 추가

---

src/component/mypage/MypagePlayList.jsx
src/component/mypage/MypagePlayList2.jsx
src/component/mypage/MypageRight.jsx
src/page/MyPage.jsx

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

feat: 오디오부분 주석처리

---

.github/CICD_DEV.yml
src/App.jsx
src/component/header/Header.jsx
src/component/main/MainPost.tsx
src/page/MainPage.tsx

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#98] 에러핸들링 수정

---

src/component/header/Header.jsx
src/component/posting/PostingAudioControlBox.tsx
src/page/PostingPage.tsx

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#98] event button 추가, 콜라보 리퀘스티드 음원  추가 삭제 버튼 제거

---

src/component/main/MainAudioPlayer.tsx
src/redux/slice/mainSlice.ts

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#98] 오디오 자동재생 차단

---

src/redux/slice/mainSlice.ts

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#98] 다른곡 재생 로직 수정

---

src/component/setpage/SetTotal.jsx

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

feat: 설정페이지 -> 마이페이지 이동

---

src/component/detail/DetailFollow.jsx
src/component/detail/detailcomment/DetailComment.jsx
src/component/detail/detailcomment/DetailCommentDeleteAndUpdate.jsx
src/component/detail/detailcomment/DetailCommentView.jsx
src/component/detail/detailcommentsub/DetailCommentSub.jsx
src/component/detail/detailcommentsub/DetailCommentSubDeleteUpdate.jsx
src/component/header/Header.jsx
src/component/mypage/MypageRight.jsx
src/component/setpage/SetTotal.jsx

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

feat: 피드백 수정

---

src/component/detail/DetailDayAndFollow.jsx
src/component/detail/DetailRecomment.jsx
src/component/mypage/MypagePlayList.jsx
src/component/mypage/MypagePlayList2.jsx

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

feat: 해시태그 수정

---

src/Router.js
src/component/chat/ChatList.tsx
src/component/chat/ChatRoomList.tsx
src/component/mypage/MypageLeft.jsx

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#96] 다이렉트 메세지로 채팅방 이동 시 추가 안되던 부분 수정, 채팅 중 유저프로필 네비게이트

---

src/component/setpage/SetTotal.jsx

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

feat:설정 페이지 수정

---

src/component/elem/Button.tsx
src/component/elem/Div.tsx
src/component/main/MainPostList.tsx
src/component/posting/PostingAudioBar.tsx
src/component/posting/PostingAudioBars.tsx
src/component/posting/PostingForm.tsx
src/component/posting/PostingFormAudio.tsx
src/component/posting/PostingFormCollabo.tsx
src/component/posting/PostingFormImage.tsx
src/component/posting/PostingTotalPlay.tsx
src/component/posting/SupportLinks.tsx
src/index.js
src/model/PostingModel.ts
src/model/StyleModel.ts
src/page/PostingPage.tsx
src/page/ServerDown.tsx
src/redux/slice/postingSlice.ts
src/styles/theme.ts

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#96] 오디어 플레이 음원 파일 추가 시 가장 긴 재생 시간 음원으로 초기화. 재생, 일시정지 로직 일부 수정

---

src/component/mypage/MypageLeft.jsx
src/component/mypage/MypagePlayList.jsx
src/component/mypage/MypagePlayList2.jsx
src/component/mypage/MypageRight.jsx
src/component/sign/KakaoLoginHandler.jsx

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

feat: 마이페이지 수정

---

src/component/mypage/MypageLeft.jsx
src/component/mypage/MypagePlayList.jsx
src/component/mypage/MypagePlayList2.jsx
src/component/mypage/MypageRight.jsx
src/component/sign/KakaoLoginHandler.jsx
src/component/sign/SignInModal.jsx
src/component/sign/SignUpModal.jsx

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

로그인 및 회원가입 로직 수정

---

src/component/main/MainAudioPlayer.tsx
src/component/main/MainPost.tsx
src/component/posting/PostingCollabReqeusted.tsx
src/component/posting/PostingForm.tsx
src/component/posting/PostingFormAudio.tsx
src/component/posting/PostingFormCollabo.tsx
src/page/PostingPage.tsx
src/redux/slice/mainSlice.ts

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#134] fix : main audio player play next/prev/different 정상 연동 확인

---

src/component/main/MainPost.tsx
src/component/main/MainPostList.tsx
src/page/MainPage.tsx
src/redux/slice/mainSlice.ts
src/redux/slice/postingSlice.ts

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#143] fix : 오타로 인한 무한스크롤 오류 해결

---

README.md
src/Router.js
src/component/main/MainPost.tsx
src/component/main/MainPostList.tsx
src/component/posting/PostingAudioBar.tsx
src/component/posting/PostingCollabReqeusted.tsx
src/component/posting/PostingForm.tsx
src/component/posting/PostingFormCollabo.tsx
src/redux/slice/mainSlice.ts

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#96] IntersectionObserver rootmargin up

---

README.md
src/App.jsx
src/Router.js
src/component/chat/ChatForm.tsx
src/component/chat/ChatRoomList.tsx
src/component/chat/chatSlice.ts
src/component/main/MainAudioPlayer.tsx
src/component/main/MainPost.tsx
src/component/main/MainPostList.tsx
src/component/posting/PostingAudioBar.tsx
src/component/posting/PostingTotalPlay.tsx
src/dataManager/apiConfig.js
src/index.js
src/redux/config/index.ts
src/redux/slice/mainSlice.ts
src/redux/slice/postingSlice.ts

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#96] 파일 정리 및 readme update

---

src/component/elem/Flex.tsx
src/component/header/Header.jsx
src/component/posting/PostingAudioBars.tsx
src/dataManager/apiConfig.js
src/modal/TypeModalContainer.js
src/modal/TypeModalWrapper.js
src/modal/modals/SearchModal.tsx
src/redux/slice/mainSlice.ts

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#79] feat: 검색기능 mvp 구현 완료

---

src/component/detail/DetailRecomment.jsx

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

feat: url 수정

---

src/component/header/Header.jsx

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#79] feat : 문자열 삭제 후 input focus 추가

---

src/component/setpage/SetTotal.jsx
src/util/Reissuance.js

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#181] refactor : setTotal page 프로필 편집 후 토큰 재발행 시 onIssued 함수 추가

---

src/component/detail/detailcomment/DetailCommentDeleteAndUpdate.jsx
src/component/detail/detailcomment/DetailCommentLike.jsx
src/component/detail/detailcommentsub/DetailCommentSubDeleteUpdate.jsx
src/component/detail/detailcommentsub/DetailCommentSubLike.jsx
src/redux/slice/comment.js
src/redux/slice/detailSlice.js

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

feat: 상세 redux 수정

---

src/component/posting/PostingForm.tsx
src/modal/modals/AlertModal.tsx
src/redux/slice/postingSlice.ts

내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.

[#96] 작성  알림 문구 수정
